QA/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questions/', include('questions.urls', namespace="questions")),
]

questions/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^about_us/$', views.about_us, name='about_us'),
	url(r'^line/$', views.line, name='line'),
	url(r'^get_name/$', views.get_name, name='get_name'),
	url(r'^handle_submission/$', views.handle_submission, name='handle_submission'),
]

questions/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def __unicode__(self):              # __unicode__ on Python 2
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_answer = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

questions/forms.py
from django import forms
from .models import *


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)
    # email = forms.EmailField(label='Email')
    # message = forms.Textarea(label='Message122')

questions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.template import loader
from django.http import Http404
from django.shortcuts import render
import pygal
from django.http import HttpResponseRedirect

# Create your views here.
def home(request):
	return HttpResponse("This is home page")

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

def index(request):
    #return HttpResponse("Hello")
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('questions/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'questions/detail.html', {'question': question})

def about_us(request):
	return render(request, 'questions/About_us.html', {})

def line(request):
	line_chart = pygal.Line()
	line_chart.title = 'Students Evaluation Results'
	line_chart.x_labels = map(str, range(2002, 2013))
	line_chart.add('Q1', [None, None, 0, 16.6,   25,   31, 36.4, 45.5, 46.3, 42.8, 37.1])
	line_chart.add('Q2',  [None, None, None, None, None, None,    0,  3.9, 10.8, 23.8, 35.3])
	line_chart.add('Q3',      [85.8, 84.6, 84.7, 74.5,   66, 58.6, 54.7, 44.8, 36.2, 26.6, 20.1])
	line_chart.add('Q4',  [10, 20 ,10, 3, 33, 55, 23, 14, 42, 4,3,44,4,4,4,4])
	line_chart.render()
	return HttpResponse(line_chart.render())

from .forms import NameForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return render(request, 'questions/successful.html', {})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'questions/name.html', {'form': form})


def handle_submission(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        print request.POST
        print "-----"*3,request.POST.get('choice1')
        form = NameForm(request.POST)
        # check whether it's valid:
        return render(request, 'questions/successful.html', {})

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'questions/name.html', {'form': form})

questions/templates/questions/About_us.html
<!--{% if latest_question_list %}-->
    <!--<ul>-->
    <!--{% for question in latest_question_list %}-->
        <!--&lt;!&ndash;<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>&ndash;&gt;-->
        <!--<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->
    <!--{% endfor %}-->
    <!--</ul>-->
<!--{% else %}-->
    <!--<p>No polls are available.</p>-->
<!--{% endif %}-->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }

    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }

    /* Add a gray background color and some padding to the footer */
    .footer {
	  background-color: #f2f2f2;
      padding: 25px;
      position: absolute
    }

  </style>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'questions:index'%}">Home</a></li>

        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span>Your Account</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="panel panel-success">
        <div class="panel-heading">Chairman</div>
        <div class="panel-body"><img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer text-right" >Info@gmail.com | 123123123</div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-success">
        <div class="panel-heading">Director</div>
        <div class="panel-body"><img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer text-right" >Info@gmail.com | 123123123</div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-success">
        <div class="panel-heading">CEO</div>
        <div class="panel-body"><img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer text-right" >Info@gmail.com | 123123123</div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-success">
        <div class="panel-heading">CTO</div>
        <div class="panel-body"><img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer text-right" >Info@gmail.com | 123123123</div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-success">
        <div class="panel-heading">HR</div>
        <div class="panel-body"><img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer text-right" >Info@gmail.com | 123123123</div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="panel panel-success">
        <div class="panel-heading">CA</div>
        <div class="panel-body"><img src="http://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image"></div>
        <div class="panel-footer text-right" >Info@gmail.com | 123123123</div>
      </div>
    </div>
  </div>
</div><br>

</body>
</html>

questions/templates/questions/Contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

questions/templates/questions/detail.html
{{ question }}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="#" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

questions/templates/questions/index.html
<!--{% if latest_question_list %}-->
    <!--<ul>-->
    <!--{% for question in latest_question_list %}-->
        <!--&lt;!&ndash;<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>&ndash;&gt;-->
        <!--<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->
    <!--{% endfor %}-->
    <!--</ul>-->
<!--{% else %}-->
    <!--<p>No polls are available.</p>-->
<!--{% endif %}-->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }

    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }

    /* Add a gray background color and some padding to the footer */
    .footer {
	  background-color: #f2f2f2;
      padding: 25px;
      position: absolute
    }

  </style>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'questions:index'%}">Home</a></li>
          <li><a href="{% url 'questions:line'%}">Analysis</a></li>
          <li><a href="{% url 'questions:about_us'%}">About Us</a></li>
          <li><a href="{% url 'questions:get_name'%}">Name Form</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span>Your Account</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
       <form action="{% url 'questions:handle_submission'%}" method="post">
       {% for question in latest_question_list %}
        <!--<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
        <div class="col-sm-12">
          <div class="panel panel-primary">
            <div class="panel-heading">Question {{ forloop.counter }} {{ question.question_text }}</div>
            <div class="panel-body"><div class="panel-heading">
                    {% csrf_token %}
                    {% for choice in question.choice_set.all %}
                        <input type="radio" name="choice{{forloop.counter}}" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                    {% endfor %}
            </div>
          </div>
          </div>
        </div>
      {% endfor %}
      <center>
          <input type="submit" class="btn btn-success" value="Submit">
          <button type="button" class="btn btn-danger">Cancel</button>
      </center>
     </form>
      <!--<div class="col-sm-4">-->
        <!--<div class="panel panel-primary">-->
          <!--<div class="panel-heading">Info Section</div>-->
          <!--<div class="panel-body"><div class="panel-heading">-->
          <!--</div>-->
        <!--</div>-->
        <!--</div>-->
      <!--</div>-->
  </div>
</div><br>

</body>
</html>

questions/templates/questions/name.html
<form action="#" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

questions/templates/questions/successful.html
<!--{% if latest_question_list %}-->
    <!--<ul>-->
    <!--{% for question in latest_question_list %}-->
        <!--&lt;!&ndash;<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>&ndash;&gt;-->
        <!--<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->
    <!--{% endfor %}-->
    <!--</ul>-->
<!--{% else %}-->
    <!--<p>No polls are available.</p>-->
<!--{% endif %}-->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default rounded borders and increase the bottom margin */
    .navbar {
      margin-bottom: 50px;
      border-radius: 0;
    }

    /* Remove the jumbotron's default bottom margin */
     .jumbotron {
      margin-bottom: 0;
    }

    /* Add a gray background color and some padding to the footer */
    .footer {
	  background-color: #f2f2f2;
      padding: 25px;
      position: absolute
    }

  </style>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'questions:index'%}">Home</a></li>

        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span>Your Account</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-success">
        <div class="panel-heading">Answers Submitted Sucessfully</div>
      </div>
    </div>
  </div>
</div><br>

</body>
</html>